// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqOnPYyl-X-sCZxI0F4O4gD1vTJm_1c0',
    appId: '1:723111602645:web:b8368fc0dd33204299755c',
    messagingSenderId: '723111602645',
    projectId: 'massmanager-a8e6b',
    authDomain: 'massmanager-a8e6b.firebaseapp.com',
    storageBucket: 'massmanager-a8e6b.firebasestorage.app',
    measurementId: 'G-XJQR5HGBBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXJI6PUT0K4WvnfIRZ1XKiynwyE8YcI6s',
    appId: '1:723111602645:android:c417c52a0c808c6299755c',
    messagingSenderId: '723111602645',
    projectId: 'massmanager-a8e6b',
    storageBucket: 'massmanager-a8e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOHLjnkMUQbhHNh8jwWLRjBU3e2uA6vkw',
    appId: '1:723111602645:ios:7599b94933f9f3bc99755c',
    messagingSenderId: '723111602645',
    projectId: 'massmanager-a8e6b',
    storageBucket: 'massmanager-a8e6b.firebasestorage.app',
    iosBundleId: 'com.example.massmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOHLjnkMUQbhHNh8jwWLRjBU3e2uA6vkw',
    appId: '1:723111602645:ios:7599b94933f9f3bc99755c',
    messagingSenderId: '723111602645',
    projectId: 'massmanager-a8e6b',
    storageBucket: 'massmanager-a8e6b.firebasestorage.app',
    iosBundleId: 'com.example.massmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqOnPYyl-X-sCZxI0F4O4gD1vTJm_1c0',
    appId: '1:723111602645:web:97818ed1bf3106de99755c',
    messagingSenderId: '723111602645',
    projectId: 'massmanager-a8e6b',
    authDomain: 'massmanager-a8e6b.firebaseapp.com',
    storageBucket: 'massmanager-a8e6b.firebasestorage.app',
    measurementId: 'G-Z4YB78KLVH',
  );
}
